export const googleSheetsSchema = {
  Classes: [
    "id",
    "programId",
    "title_en",
    "title_fr",
    "title_zh",
    "ageGroup",
    "level_en",
    "level_fr",
    "level_zh",
    "schedule_en",
    "schedule_fr",
    "schedule_zh",
    "capacity",
    "reserved",
    "active"
  ],
  Events: [
    "id",
    "title_en",
    "title_fr",
    "title_zh",
    "date",
    "location_en",
    "location_fr",
    "location_zh",
    "summary_en",
    "summary_fr",
    "summary_zh",
    "type",
    "featured"
  ],
  Media: [
    "id",
    "kind",
    "eventId",
    "title_en",
    "title_fr",
    "title_zh",
    "driveFileId",
    "publicUrl",
    "thumbnailUrl",
    "featured"
  ],
  Inquiries: [
    "id",
    "createdAt",
    "status",
    "inquiryType",
    "classId",
    "eventId",
    "bookingAction",
    "ticketLinksShownAt",
    "studentName",
    "age",
    "guardianName",
    "email",
    "phone",
    "preferredLanguage",
    "preferredSchedule",
    "experience",
    "message"
  ],
  Partners: [
    "id",
    "name",
    "type",
    "contact",
    "notes",
    "active"
  ],
  Settings: ["key", "value_en", "value_fr", "value_zh"]
};
